""" Karr Lab build utilities

:Author: Jonathan Karr <karr@mssm.edu>
:Date: 2017-08-02
:Copyright: 2016, Karr Lab
:License: MIT
"""

from coverage import coverage
from coveralls import Coveralls
from ftputil import FTPHost
from glob import glob
from junit2htmlreport.parser import Junit as JunitParser
from nose2unitth.core import Converter as Nose2UnitthConverter
from sphinx import build_main as sphinx_build
from sphinx.apidoc import main as sphinx_apidoc
from unitth.core import UnitTH
import git
import nose
import os
import pip
import shutil
import subprocess
import sys
import tempfile


class BuildHelper(object):
    """ Utility class to help build projects:
    * Run tests
    * Generate HTML test history reports
    * Generate HTML coverage reports
    * Generate HTML API documentation
    * Archive reports to lab server and Coveralls

    Attributes:
        code_server_hostname (:obj:`str`): hostname of server where reports should be uploaded
        code_server_username (:obj:`str`): username for server where reports should be uploaded
        code_server_password (:obj:`str`): password for server where reports should be uploaded
        code_server_base_dir (:obj:`str`): base directory on server where reports should be uploaded

        project_name (:obj:`str`): name of project, e.g. GitHub repository name
        build_num (:obj:`int`): CircleCI build number

        proj_tests_dir (:obj:`str`): local directory with test code
        proj_tests_nose_latest_filename (:obj:`str`): file name to store latest XML test report
        proj_tests_nose_dir (:obj:`str`): local directory where the test reports generated by nose should be saved
        proj_tests_unitth_dir (:obj:`str`): local directory where UnitTH input should be saved
        proj_tests_html_dir (:obj:`str`): local directory where HTML test history report should be saved
        proj_cov_filename (:obj:`str`): file name where coverage report should be saved
        proj_cov_html_dir (:obj:`str`): local directory where HTML coverage report should be saved
        proj_docs_dir (:obj:`str`): local directory with Sphinx configuration
        proj_docs_static_dir (:obj:`str`): local directory of static documentation files
        proj_docs_source_dir (:obj:`str`): local directory of source documentation files created by sphinx-apidoc
        proj_docs_build_html_dir (:obj:`str`): local directory where generated HTML documentation should be saved

        serv_tests_nose_dir (:obj:`str`): server directory where the test reports generated by nose should be saved
        serv_tests_unitth_dir (:obj:`str`): server directory where UnitTH input should be saved
        serv_tests_html_dir (:obj:`str`): server directory where HTML test history report should be saved
        serv_cov_html_dir (:obj:`str`): server directory where HTML coverage report should be saved
        serv_docs_build_html_dir (:obj:`str`): server directory where generated HTML documentation should be saved

        coveralls_token (:obj:`str`): coveralls token

        build_artifacts_dir (:obj:`str`): directory which CircleCI will record with each build
        build_test_dir (:obj:`str`): directory where CircleCI will look for test results
    """

    DEFAULT_CODE_SERVER_HOSTNAME = 'code.karrlab.org'
    # :obj:`str`: default hostname of server where reports should be uploaded

    DEFAULT_CODE_SERVER_USERNAME = 'karrlab_code'
    # :obj:`str`: default username for server where reports should be uploaded

    DEFAULT_CODE_SERVER_BASE_DIR = '/code.karrlab.org'
    # :obj:`str`: default base directory on server where reports should be uploaded

    DEFAULT_PROJ_TESTS_DIR = 'tests'
    # :obj:`str`: default local directory with test code

    DEFAULT_PROJ_TESTS_NOSE_LATEST_FILENAME = 'latest'
    # :obj:`str`: default file name to store latest XML test report

    DEFAULT_PROJ_TESTS_NOSE_DIR = 'tests/reports/nose'
    # :obj:`str`: default local directory where the test reports generated by nose should be saved

    DEFAULT_PROJ_TESTS_UNITTH_DIR = 'tests/reports/unitth'
    # :obj:`str`: default local directory where UnitTH input should be saved

    DEFAULT_PROJ_TESTS_HTML_DIR = 'tests/reports/html'
    # :obj:`str`: default local directory where HTML test history report should be saved

    DEFAULT_PROJ_COV_FILENAME = '.coverage'
    # :obj:`str`: default coverage file name

    DEFAULT_PROJ_COV_HTML_DIR = 'tests/reports/coverage'
    # :obj:`str`: default local directory where HTML coverage report should be saved

    DEFAULT_PROJ_DOCS_DIR = 'docs'
    # :obj:`str`: default local directory with Sphinx configuration

    DEFAULT_PROJ_DOCS_STATIC_DIR = 'docs/_static'
    # :obj:`str`: default local directory of static documentation files

    DEFAULT_PROJ_DOCS_SOURCE_DIR = 'docs/source'
    # :obj:`str`: default local directory of source documentation files created by sphinx-apidoc

    DEFAULT_PROJ_DOCS_BUILD_HTML_DIR = 'docs/_build/html'
    # :obj:`str`: default local directory where generated HTML documentation should be saved

    DEFAULT_SERV_TESTS_NOSE_DIR = 'tests/nose'
    # :obj:`str`: default server directory where the test reports generated by nose should be saved

    DEFAULT_SERV_TESTS_UNITTH_DIR = 'tests/unitth'
    # :obj:`str`: default server directory where UnitTH input should be saved

    DEFAULT_SERV_TESTS_HTML_DIR = 'tests/html'
    # :obj:`str`: default server directory where HTML test history report should be saved

    DEFAULT_SERV_COV_HTML_DIR = 'tests/coverage'
    # :obj:`str`: default server directory where HTML coverage report should be saved

    DEFAULT_SERV_DOCS_BUILD_HTML_DIR = 'docs'
    # :obj:`str`: default server directory where generated HTML documentation should be saved

    def __init__(self):
        """ Construct build helper """

        # get settings from environment variables
        self.code_server_hostname = os.getenv('CODE_SERVER_HOSTNAME', BuildHelper.DEFAULT_CODE_SERVER_HOSTNAME)
        self.code_server_username = os.getenv('CODE_SERVER_USERNAME', BuildHelper.DEFAULT_CODE_SERVER_USERNAME)
        self.code_server_password = os.getenv('CODE_SERVER_PASSWORD')
        self.code_server_base_dir = os.getenv('CODE_SERVER_BASE_DIR', BuildHelper.DEFAULT_CODE_SERVER_BASE_DIR)

        self.project_name = os.getenv('CIRCLE_PROJECT_REPONAME', '')
        if not self.project_name:
            try:
                repo = git.Repo('.')
                self.project_name, _ = os.path.splitext(os.path.basename(repo.remote().url))
            except git.exc.InvalidGitRepositoryError as err:
                pass
        self.build_num = int(float(os.getenv('CIRCLE_BUILD_NUM', 0)))

        self.proj_tests_dir = BuildHelper.DEFAULT_PROJ_TESTS_DIR
        self.proj_tests_nose_latest_filename = BuildHelper.DEFAULT_PROJ_TESTS_NOSE_LATEST_FILENAME
        self.proj_tests_nose_dir = BuildHelper.DEFAULT_PROJ_TESTS_NOSE_DIR
        self.proj_tests_unitth_dir = BuildHelper.DEFAULT_PROJ_TESTS_UNITTH_DIR
        self.proj_tests_html_dir = BuildHelper.DEFAULT_PROJ_TESTS_HTML_DIR
        self.proj_cov_filename = BuildHelper.DEFAULT_PROJ_COV_FILENAME
        self.proj_cov_html_dir = BuildHelper.DEFAULT_PROJ_COV_HTML_DIR
        self.proj_docs_dir = BuildHelper.DEFAULT_PROJ_DOCS_DIR
        self.proj_docs_static_dir = BuildHelper.DEFAULT_PROJ_DOCS_STATIC_DIR
        self.proj_docs_source_dir = BuildHelper.DEFAULT_PROJ_DOCS_SOURCE_DIR
        self.proj_docs_build_html_dir = BuildHelper.DEFAULT_PROJ_DOCS_BUILD_HTML_DIR

        self.serv_tests_nose_dir = BuildHelper.DEFAULT_SERV_TESTS_NOSE_DIR
        self.serv_tests_unitth_dir = BuildHelper.DEFAULT_SERV_TESTS_UNITTH_DIR
        self.serv_tests_html_dir = BuildHelper.DEFAULT_SERV_TESTS_HTML_DIR
        self.serv_cov_html_dir = BuildHelper.DEFAULT_SERV_COV_HTML_DIR
        self.serv_docs_build_html_dir = BuildHelper.DEFAULT_SERV_DOCS_BUILD_HTML_DIR

        self.coveralls_token = os.getenv('COVERALLS_REPO_TOKEN')

        self.build_artifacts_dir = os.getenv('CIRCLE_ARTIFACTS')
        self.build_test_dir = os.getenv('CIRCLE_TEST_REPORTS')

    ########################
    # Installing dependencies
    ########################
    def install_requirements(self):
        """ Install requirements """

        # requirements for package
        with open('requirements.txt', 'r') as file:
            reqs = [line.rstrip() for line in file.readlines()]
        pip.main(['install'] + reqs)

        # requirements for testing and documentation
        subprocess.check_call(['sudo', 'apt-get', 'install', 'libffi-dev'])

        with open(os.path.join(self.proj_tests_dir, 'requirements.txt'), 'r') as file:
            reqs = [line.rstrip() for line in file.readlines()]
        pip.main(['install'] + reqs)

        with open(os.path.join(self.proj_docs_dir, 'requirements.txt'), 'r') as file:
            reqs = [line.rstrip() for line in file.readlines()]
        pip.main(['install'] + reqs)

    ########################
    # Running tests
    ########################
    def run_tests(self, test_path='tests', with_xunit=False, with_coverage=False):
        """ Run unit tests located at `test_path`.
        Optionally, generate a coverage report.
        Optionally, save the results to `xml_file`.

        Args:
            test_path (:obj:`str`, optional): path to tests that should be run
            with_coverage (:obj:`bool`, optional): whether or not coverage should be assessed
            xml_file (:obj:`str`, optional): path to save test results

        Raises:
            :obj:`BuildHelperError`: If package directory not set
        """

        py_v = BuildHelper.get_python_version()
        abs_nose_latest_filename = os.path.join(
            self.proj_tests_nose_dir, '{0}.{1}.xml'.format(self.proj_tests_nose_latest_filename, py_v))

        argv = ['nosetests', test_path]

        if with_xunit:
            argv.append('--with-xunit')
            
            argv.append('--xunit-file')
            argv.append(abs_nose_latest_filename)

            if not os.path.isdir(self.proj_tests_nose_dir):
                os.makedirs(self.proj_tests_nose_dir)

        if with_coverage:
            cov = coverage(data_file='.coverage', data_suffix=py_v)
            cov.start()

        result = nose.run(argv=argv)

        if with_coverage:
            cov.stop()
            cov.save()

        if with_xunit and self.build_test_dir:
            abs_nose_artifact_filename = os.path.join(self.build_test_dir, '{0}.{1}.xml'.format('nose', py_v))
            shutil.copyfile(abs_nose_latest_filename, abs_nose_artifact_filename)

        if not result:
            sys.exit(1)

    def make_and_archive_reports(self):
        """ Make and archive reports;
        * Generate HTML test history reports
        * Generate HTML coverage reports
        * Generate HTML API documentation
        * Archive coverage report to Coveralls
        * Archive HTML coverage report to lab sever
        """

        """ test reports """
        # create directory with test result history
        self.download_nose_test_report_history_from_lab_server()

        for file in glob(os.path.join(self.proj_tests_nose_dir, '{0}.{1}.xml'.format(self.proj_tests_nose_latest_filename, '*'))):
            shutil.copyfile(file, file.replace(self.proj_tests_nose_latest_filename, str(self.build_num)))

        # make report of test history
        self.make_test_history_report()

        # copy test history to lab server
        self.archive_test_reports()

        """ coverage """
        # Merge coverage reports
        # Generate HTML report
        # Copy coverage report to artifacts directory
        # Upload coverage report to Coveralls
        # Upload HTML coverage report to lab server
        self.combine_coverage_reports()
        self.make_html_coverage_report()
        self.archive_coverage_report()

        """ documentation """
        self.make_documentation()
        self.archive_documentation()

    ########################
    # Test reports
    ########################

    def download_nose_test_report_history_from_lab_server(self):
        """ Download XML test report history from lab server """

        if not os.path.isdir(self.proj_tests_nose_dir):
            os.makedirs(self.proj_tests_nose_dir)
        for report_filename in glob(os.path.join(self.proj_tests_nose_dir, "[0-9]*.*.xml")):
            os.remove(report_filename)

        with self.get_connection_to_lab_server() as ftp:
            self.download_dir_from_lab_server(ftp, self.serv_tests_nose_dir, self.proj_tests_nose_dir)

    def make_test_history_report(self):
        """ Make an HTML test history report from a directory of nose-style XML test reports """

        if not os.path.isdir(self.proj_tests_unitth_dir):
            os.makedirs(self.proj_tests_unitth_dir)

        # remove old UnitTH input
        for path in os.listdir(self.proj_tests_unitth_dir):
            full_path = os.path.join(self.proj_tests_unitth_dir, path)
            if os.path.isdir(full_path):
                shutil.rmtree(full_path)
            else:
                os.remove(full_path)

        # Make XML and HTML test reports that are readable UnitTH
        for build_file_path in glob(os.path.join(self.proj_tests_nose_dir, "[0-9]*.*.xml")):
            build_base_name = os.path.basename(build_file_path)
            build_num_py_v = os.path.splitext(build_base_name)[0]

            # Split nose-style XML report into UnitTH-style reports for each package
            if not os.path.isdir(os.path.join(self.proj_tests_unitth_dir, build_num_py_v)):
                os.makedirs(os.path.join(self.proj_tests_unitth_dir, build_num_py_v))

            Nose2UnitthConverter.run(build_file_path, os.path.join(self.proj_tests_unitth_dir, build_num_py_v))

            # Make HTML report from nose-style test XML report
            with open(os.path.join(os.path.join(self.proj_tests_unitth_dir, build_num_py_v, 'index.html')), 'wb') as html_file:
                html_file.write(JunitParser(build_file_path).html().encode('utf-8'))

        # Make HTML test history report
        if not os.path.isdir(self.proj_tests_html_dir):
            os.makedirs(self.proj_tests_html_dir)

        UnitTH.run(os.path.join(self.proj_tests_unitth_dir, '*'),
                   xml_report_filter='',
                   html_report_path='.',
                   generate_exec_time_graphs=True,
                   html_report_dir=self.proj_tests_html_dir)

    def archive_test_reports(self):
        """ Archive test report:
        * Upload XML and HTML test reports to lab server
        """

        self.upload_test_reports_to_lab_server()

    def upload_test_reports_to_lab_server(self):
        """ Upload XML and HTML test reports to lab server """

        with self.get_connection_to_lab_server() as ftp:
            if not ftp.path.isdir(self.serv_tests_nose_dir):
                ftp.makedirs(self.serv_tests_nose_dir)

            for name in glob(os.path.join(self.proj_tests_nose_dir, '{0:d}.{1:s}.xml'.format(self.build_num, '*'))):
                ftp.upload(name, self.serv_tests_nose_dir + name[len(self.proj_tests_nose_dir):])

            for name in glob(os.path.join(self.proj_tests_unitth_dir, '{0:d}.{1:s}'.format(self.build_num, '*'))):
                self.upload_dir_to_lab_server(ftp, name, self.serv_tests_unitth_dir +
                                              name[len(self.proj_tests_unitth_dir):])

            self.upload_dir_to_lab_server(ftp, self.proj_tests_html_dir, self.serv_tests_html_dir)

    ########################
    # Coverage reports
    ########################
    def combine_coverage_reports(self):
        data_paths = []
        for name in glob('.coverage.*'):
            data_path = tempfile.mktemp()
            shutil.copyfile(name, data_path)
            data_paths.append(data_path)

        coverage_doc = coverage()
        coverage_doc.combine(data_paths=data_paths)
        coverage_doc.save()

    def make_html_coverage_report(self):
        """ Make HTML coverage report from `proj_cov_filename` """
        if not os.path.isdir(self.proj_cov_html_dir):
            os.makedirs(self.proj_cov_html_dir)
        map(os.remove, glob(os.path.join(self.proj_cov_html_dir, '*')))
        coverage_doc = coverage(data_file='.coverage')
        coverage_doc.load()
        coverage_doc.html_report(directory=self.proj_cov_html_dir)

    def archive_coverage_report(self):
        """ Archive coverage report:
        * Copy report to artifacts directory
        * Upload report to Coveralls
        * Upload HTML report to lab server
        """

        # copy to artifacts directory
        self.copy_coverage_report_to_artifacts_directory()

        # upload to Coveralls
        self.upload_coverage_report_to_coveralls()

        # upload to lab server
        self.upload_html_coverage_report_to_lab_server()

    def copy_coverage_report_to_artifacts_directory(self):
        """ Copy coverage report to CircleCI artifacts directory """
        if self.build_artifacts_dir:
            for name in glob('.coverage.*'):
                shutil.copyfile(name, os.path.join(self.build_artifacts_dir, name))

    def upload_coverage_report_to_coveralls(self):
        """ Upload coverage report to Coveralls """
        if self.coveralls_token:
            Coveralls(True, repo_token=self.coveralls_token,
                      service_name='circle-ci', service_job_id=self.build_num).wear()

    def upload_html_coverage_report_to_lab_server(self):
        """ Upload HTML coverage report to lab server """

        with self.get_connection_to_lab_server() as ftp:
            self.upload_dir_to_lab_server(ftp, self.proj_cov_html_dir, self.serv_cov_html_dir)

    ########################
    # Documentation
    ########################

    def make_documentation(self):
        """ Make HTML documentation using Sphinx for one or more packages. Save documentation to `proj_docs_build_html_dir` 

        Raises:
            :obj:`BuildHelperError`: If project name or code server password not set
        """

        # create `proj_docs_static_dir`, if necessary
        if not os.path.isdir(self.proj_docs_static_dir):
            os.mkdir(self.proj_docs_static_dir)

        # compile API documentation
        from ConfigParser import ConfigParser
        parser = ConfigParser()
        parser.read('setup.cfg')
        packages = parser.get('sphinx-apidocs', 'packages').strip().split('\n')
        for package in packages:
            sphinx_apidoc(argv=['sphinx-apidoc', '-f', '-o', self.proj_docs_source_dir, package])

        # build HTML documentation
        result = sphinx_build(['sphinx-build', self.proj_docs_dir, self.proj_docs_build_html_dir])
        if result != 0:
            sys.exit(result)

    def archive_documentation(self):
        """ Archive documentation:
        * Upload documentation to lab server
        """

        self.upload_documentation_to_lab_server()

    def upload_documentation_to_lab_server(self):
        """ Upload documentation to lab server """

        with self.get_connection_to_lab_server() as ftp:
            self.upload_dir_to_lab_server(ftp, self.proj_docs_build_html_dir, self.serv_docs_build_html_dir)

    def get_connection_to_lab_server(self):
        """ Connect to lab server

        Raises:
            :obj:`BuildHelperError`: If project name or code server password not set
        """

        if not self.project_name:
            raise BuildHelperError('Project name not set')

        if not self.code_server_password:
            raise BuildHelperError('Code server password must be set')

        ftp = FTPHost(self.code_server_hostname, self.code_server_username, self.code_server_password)
        if not ftp.path.isdir(ftp.path.join(self.code_server_base_dir, self.project_name)):
            ftp.makedirs(ftp.path.join(self.code_server_base_dir, self.project_name))
        ftp.chdir(ftp.path.join(self.code_server_base_dir, self.project_name))

        return ftp

    def upload_dir_to_lab_server(self, ftp, local_root_dir, remote_root_dir):
        """ Upload directory to lab server

        Args:
            ftp (:obj:`ftputil.FTPHost`): FTP connection
            local_root_dir (:obj:`str`): local directory to upload
            remote_root_dir (:obj:`str`): remote path to copy local directory to
        """
        for local_dir, _, local_files in os.walk(local_root_dir, onerror=self.walk_error):
            if local_dir == local_root_dir:
                rel_dir = '.'
            else:
                rel_dir = local_dir[len(local_root_dir) + 1:]

            if not ftp.path.isdir(ftp.path.join(remote_root_dir, rel_dir)):
                ftp.makedirs(ftp.path.join(remote_root_dir, rel_dir))
            for local_file in local_files:
                ftp.upload(os.path.join(local_root_dir, rel_dir, local_file),
                           ftp.path.join(remote_root_dir, rel_dir, local_file))

    def download_dir_from_lab_server(self, ftp, remote_root_dir, local_root_dir):
        """ Download directory from lab server

        Args:
            ftp (:obj:`ftputil.FTPHost`): FTP connection
            remote_root_dir (:obj:`str`): remote directory to download
            local_root_dir (:obj:`str`): local path to copy remote directory to
        """
        if not ftp.path.isdir(remote_root_dir):
            ftp.makedirs(remote_root_dir)

        for remote_dir, _, remote_files in ftp.walk(remote_root_dir, onerror=self.walk_error):
            if remote_dir == remote_root_dir:
                rel_dir = '.'
            else:
                rel_dir = remote_dir[len(remote_root_dir) + 1:]
            if not os.path.isdir(os.path.join(local_root_dir, rel_dir)):
                os.makedirs(os.path.join(local_root_dir, rel_dir))
            for remote_file in remote_files:
                ftp.download(ftp.path.join(remote_root_dir, rel_dir, str(remote_file)),
                             os.path.join(local_root_dir, rel_dir, remote_file))

    def walk_error(self, err):
        """ Throw error during os or ftp walk

        Args:
            err: Error in os or ftp walk

        Raises:
            :obj:`BuildHelperError`
        """
        raise BuildHelperError(err)

    @staticmethod
    def get_python_version():
        return '{0[0]:d}.{0[1]:d}.{0[2]:d}'.format(sys.version_info)


class BuildHelperError(Exception):
    """ Represents :obj:`BuildHelper` errors """
    pass
